version: '3.8'

services:
  booking-service:
    build: ./services/booking-service
    container_name: booking-service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001

  user-profile-service:
    build: ./services/user-profile-service
    container_name: user-profile-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
