version: '3.8'

services:
  booking-service:
    build: ./services/booking-service
    container_name: booking-service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001

  user-profile-service:
    build: ./services/user-profile-service
    container_name: user-profile-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      
  message-service:
    build: ./services/message-service
    container_name: message-service
    ports:
      - "4003:4003"
    environment:
      - PORT=4003

  frontend:
    build: ./app
    container_name: consultnow-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - booking-service
      - user-profile-service
      - message-service