/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "eu-north-1",
  "aws_cognito_identity_pool_id": "eu-north-1:8d2d53da-8d9d-4c88-9b75-570a9685fd9e", // Update with your actual Identity Pool ID
  "aws_cognito_region": "eu-north-1",
  "aws_user_pools_id": "eu-north-1_8yPX9gkFI",
  "aws_user_pools_web_client_id": process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
  "oauth": {
    "domain": process.env.NEXT_PUBLIC_COGNITO_DOMAIN?.replace(/^https?:\/\//, ''),
    "redirectSignIn": process.env.NEXT_PUBLIC_COGNITO_REDIRECT_URL,
    "redirectSignOut": process.env.NEXT_PUBLIC_COGNITO_LOGOUT_URI,
    "responseType": "code"
  },
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ]
};

export default awsmobile;